### PR TITLE
MPDX-232 Chalkline Integration

### PR DESCRIPTION
**Pull request by draffensperger**
This adds a button that will queue a job to send a CSV attachment for the current account list's paper mailing list to Chalkline and CC the users.

### CODE REVIEW

**Comment by draffensperger** [comment]
@soberstadt Stacie asked for the button to open the form in a new tab. When I just to '_blank' for the link_to, that would work

**Comment by draffensperger** [comment]
@soberstadt Stacie asked for the chalkline order form to be opened in a new tab. I can do `target="_blank"`, but that would be without a confirmation dialog, but I'd like to do a confirmation dialog and not trigger the popup blocker. If I do a click handler like I did it works. But I'm using the default Javascript `window.conform` confirmation dialog. Do you have any ideas for how to get the regular Rails confirmation dialog there? I suppose I'd need to capture the click on the "Yes" button for it.

**Comment by draffensperger** [comment]
Turns out I can capture the `rails.click` event which it sends on confirmation (and when it's first clicked), and I can just check to see if it still needs to be confirmed. Let me know if there's a smarter solution you can think of.

This was my initial attempt which is more elegant:
```
link_to(_('Send ..'), 'http://www.chalkline.org/order_mpdx.htm', class: 'btn',
                          data: {method: :get, confirm: _("Would you like ..")},
                          target: '_blank')
```
And that almost works, except that the `method: :get` isn't a regular GET (uses a special method header for the delete, etc. I believe), so Chalkline actually gets a post message for their page in a new tab which crashes it with an unexpected http verb error.

**Comment by soberstadt** [comment]
Probably the best way to do this then is to have the confirmation window ask if its alright to send them your contacts' information, then have a second link appear to go to the order form. You could then use js to click the link, which may get stopped by the pop-up blocker, but then the user can still click the button.

But I'm a little confused by what you're proposing with rails.click... I might need more code to understand that.

**Comment by draffensperger** [comment]
That's a clever idea, but I guess as I reflect on it that if this current solution works, to stick with it and it actually will probably only be used by a minority of MPDX users about once per month. I did want to be relatively confident that it wouldn't trigger pop-up blockers though so I tried it on Safari, Chrome and Firefox and they all opened a separate tab and then focused that tab which is the behavior we would want.

For the `rails.click` event, I looked into it and from the way we customized the Rails confirm dialog (see https://github.com/CruGlobal/mpdx/blob/master/app/assets/javascripts/mpdx.js.coffee#L126), the `rails.click` event is triggered once the confirm dialog is complete, so trapping it makes sense actually.

@soberstadt or @twinge, how does the feature look overall?

**Comment by soberstadt** [comment]
I think the code is understandable and if it works then I'm good with it. I'm glad you got this working!

**Pull request merged**
