### PR TITLE
Import appeals from Tnt

### PR DESCRIPTION
**Pull request by draffensperger**
To avoid a Rubocop error on the file size, I move some more methods into `TnImportUtil`. I also made it import the Tnt "Never ask" field into the `no_appeals` field in Contact. When Adam and I were working on the appeals tracking stuff earlier I had assumed that field wasn't in MPDX. We've coded the appeal tracking to use the new `no_appeals` field instead of the older `never_ask` field (oops, didn't realize there was already a field for it there!).

As part of deploying this though, we should capture the already imported Tnt "Never ask" data, so I'd run the following code to move that data over to the newer `no_appeals` field:

    Contact.where(never_ask: true).find_each { |c| c.update_column(:no_appeals, true) }

### CODE REVIEW

**Comment by twinge** [comment]
I'm not tracking with you why we'd want to store Tnt's 'Never Ask' value in the no_appeals column instead of our never_ask column.

**Comment by draffensperger** [comment]
Basically just because me and Adam wrote out the UI and back end logic for the appeals feature to use `no_appeals` (it's in the edit contact page and the create appeals page and underlying backend code). Do you think it would be better to just go back and make it use the `never_ask` field instead? (And sort of do the reverse update to get any set `no_appeals` data into `never_ask`?)

**Comment by twinge** [comment]
Yes, i think it would be more consistent to change what you did to use the field that was there before.

**Comment by twinge** [comment]
Does setting the contact status to 'Never Ask' affect that field at all? I just don't remember.

**Comment by draffensperger** [comment]
OK, I'll plan to amend this to replace our usage of `no_appeals` with `never_ask`.

No, setting the contact status to "Never Ask" doesn't affect that. The meaning of the "Never Ask" status is "don't ever ask this person for support in any way" and the meaning of the `never_ask` field in MPDX (and the corresponding "Never Ask" checkbox in Tnt) is "never send this person special gift appeals (even if they are say, a regular financial partner)".

An example for me that comes to mind of when the do-not-send-appeals checkbox could be useful would be say a family member who give monthly but who you wouldn't want to send your special asks to. I'm sure there would be other cases it could be helpful too.

**Comment by twinge** [comment]
hmm. in that case you may have convinced me that no_appeals is a better name, but it looks like you made the change already :)

**Comment by draffensperger** [comment]
Was pretty easy to change with the search feature. I think if you're OK with using `no_appeals` that definitely is clearer for someone reading the code. As a Tnt user I never understood what the "Never Ask" checkbox did. I think I may have actually only learned when Stacie explained it to me for this appeals tracking in MPDX!

**Comment by twinge** [comment]
Yeah, i agree that it's more clear. Part of the data cleanup/migration should be to delete the never_ask column to prevent future confusion

**Comment by soberstadt** [comment]
I'm glad yall had the convo here, because I was going to say the same thing. You should make your update all columns command a part of the migration, right before you delete the old field. Kind of like Justin's migration: https://github.com/CruGlobal/mpdx/pull/260/files#diff-838ef7fc2f6ff964686948cb6c4ad77bR3

**Comment by soberstadt** [comment]
So what is the purpose of the TntImportUtil model? How do you distinguish what methods should go where?

**Comment by draffensperger** [comment]
@soberstadt For the `TntImportUtil` I did it mostly just to avoid getting the Rubocop error. I started by just putting small functions whose behavior wasn't central to the main logic of the Tnt import in, but this time added some more which are somewhat arbitrary (not really a clean design). What's your opinion, do you think we'd be better just turning off the cop for the Tnt import, or what might be a clean way to split up the code?

**Comment by draffensperger** [comment]
After chatting with Spencer on this I have disable the class size cop for `TntImport` and just pulled in the code that was in the `TntImportUtil` into the main `TntImport` class and got rid of the module. Are we good to merge?

**Comment by twinge** [comment]
:+1:

**Pull request merged**
