### PR TITLE
MPDX 167 - contact details editable on /show

### PR DESCRIPTION
**Pull request by soberstadt**
This PR is to cover everything for the feature of editing contact details right from /show

Josh started this (8fdca34684edba10e67f1e55fb16797dd88f9533), but I wanted to make a checklist of things we think need to be worked on:
- [x] initial feature
- [x] visual feedback on contact save
- [X] something to show users that they can edit the field

### CODE REVIEW

**Comment by soberstadt** [comment]
PS, this uses the [best_in_place](https://github.com/bernat/best_in_place) lib

**Comment by soberstadt** [comment]
screenshot 2015-02-23 09 44 39
Here's what it looks like with some feedback that the fields can be clicked on.

What do you guys think of this?

**Comment by twinge** [comment]
I like it

On Mon, Feb 23, 2015 at 7:48 AM, Spencer Oberstadt <notifications@github.com

**Comment by draffensperger** [comment]
Looks good to me. You may be implementing this soon, but if the pledge amount is editable, I'd think we'd need the pledge frequency to be editable too.

**Comment by soberstadt** [comment]
@twinge, wasn't the frequency editable at one point? do you remember why you took it off?

**Comment by twinge** [comment]
It was very briefly, but i never got it working right with the plugin i was
using. It'd be nice if it worked

On Mon, Feb 23, 2015 at 9:25 AM, Spencer Oberstadt <notifications@github.com

**Comment by soberstadt** [comment]
This is ready for final review.

**Comment by soberstadt** [comment]
Updated screenshot: https://www.dropbox.com/s/dfibhfwbun3tgzu/Screenshot%202015-02-24%2014.01.37.png?dl=0

**Pull request merged**
