### PR TITLE
prayer reqest option added

### PR DESCRIPTION
**Pull request by chencuicru**

### CODE REVIEW

**Comment by twinge** [comment]
What's the jira issue number for this?

**Comment by chencuicru** [comment]
MPDX-279

On Wed, Feb 18, 2015 at 11:57 AM, Josh Starcher <notifications@github.com>
wrote:

> What's the jira issue number for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CruGlobal/mpdx/pull/281#issuecomment-74901173>.
>



-- 
*Chen Cui   *
Siebel Developer
Digital Strategies, Cru
407-826-2429
chen.cui@cru.org

**Comment by twinge** [comment]
Why did you close this?

**Comment by chencuicru** [comment]
Travis ask me to align the lines.  So after the alignment, I did a push and
the push failed saying the remote branch is ahead of local branch.  That is
because I did a rebase with the master.  So I had to close and delete the
pull request and do another push and reopen the pull request.

On Wed, Feb 18, 2015 at 1:48 PM, Josh Starcher <notifications@github.com>
wrote:

> Why did you close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CruGlobal/mpdx/pull/281#issuecomment-74922588>.
>



-- 
*Chen Cui   *
Siebel Developer
Digital Strategies, Cru
407-826-2429
chen.cui@cru.org

**Comment by soberstadt** [comment]
In the future, if you rebase on master (which is what you’re supposed to do when working on a branch), you can force push that particular branch to override what is on github.

**Comment by chencuicru** [comment]
Thanks, just getting familiar with the steps now.

On Wed, Feb 18, 2015 at 2:07 PM, Spencer Oberstadt <notifications@github.com
> wrote:

> In the future, if you rebase on master (which is what you’re supposed to
> do when working on a branch), you can force push that particular branch to
> override what is on github.
>
> On Wed, Feb 18, 2015 at 1:04 PM, chen cui <notifications@github.com>
> wrote:
>
> > Travis ask me to align the lines. So after the alignment, I did a push
> and
> > the push failed saying the remote branch is ahead of local branch. That
> is
> > because I did a rebase with the master. So I had to close and delete the
> > pull request and do another push and reopen the pull request.
> > On Wed, Feb 18, 2015 at 1:48 PM, Josh Starcher <notifications@github.com
> >
> > wrote:
> >> Why did you close this?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/CruGlobal/mpdx/pull/281#issuecomment-74922588>.
> >>
> > --
> > *Chen Cui *
> > Siebel Developer
> > Digital Strategies, Cru
> > 407-826-2429
> > chen.cui@cru.org
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/CruGlobal/mpdx/pull/281#issuecomment-74925719
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CruGlobal/mpdx/pull/281#issuecomment-74926134>.
>



-- 
*Chen Cui   *
Siebel Developer
Digital Strategies, Cru
407-826-2429
chen.cui@cru.org

**Pull request closed without merging**
