### PR TITLE
Implement larger gift notification

### PR DESCRIPTION
**Pull request by draffensperger**
This was already started, just added the implementation. Made it so that it checks by monthly total not by individual gift amount. I actually had a case last summer of a $50/month partner who made a $50 special gift for our summer ask, so this would capture that.

There are partners who sometimes give by check and make their next gift right at the end of the month when their last gift was right at the beginning, but with thank you reminders, better to notify in that case and let the user decide whether to ignore it or actually send a thank you.

### CODE REVIEW

**Comment by draffensperger** [comment]
Hadn't added spec file when first pushed, added it now.

**Comment by jbirdjavi** [comment]
Does this work for non-monthly donors?

**Comment by draffensperger** [comment]
Well, it doesn't check the pledge frequency at all. So if someone gives $1000/year and gives over $1000 in any given month, that will trigger the notification. But you raise a good point - what if someone pledges $1000/yr and gives $600 one month and $600 another month? Maybe what we really need is a separate notification (or just change the messages and logic a bit for this) for when someone gives less, but gives less than their pledged amount in a given month. Thoughts?

**Comment by draffensperger** [comment]
Here's another idea: what if we had pledge frequencies 1-4 (monthly through 3 times / year) trigger a notification if their giving for the past N months was higher than their pledge (analogous to the monthly case), and then for people who give 1-2 times per year, just send a notification every time they give. It's typically wise to thank annual partners every year when they give. I'll ask Stacie for her thoughts on this too.

**Comment by jbirdjavi** [comment]
I think the best solution would be to check the pledge frequency somehow.  But what the threshold of notifying whether there's a larger/smaller gift and how many time periods ago to check would probably be more in Stacie's court...

**Comment by draffensperger** [comment]
Stacie gave me some feedback on this, and yeah, I need to more carefully handle cases of various frequencies. I'm closing this for now. Will re-open with the fixes.

**Pull request closed without merging**
