### PR TITLE
Add check for retried or running dup Sidekiq job

### PR DESCRIPTION
**Pull request by draffensperger**
The `sidekiq-unique-jobs` gem does not preserve uniqueness if a job is in the retry queue or if a Sidekiq process crashes and the Sidekiq pro job recovery feature gets used. This code is a quick fix to break out of jobs that are in the retry queue or have a duplicate, older job running already. I've tested it locally with some simple test workers and it does indeed exit out of duplicate jobs right away. My suggestion would be to merge this to stage first and then if there are no issues there and the background jobs work correctly to merge it into master.

I think this code should ultimately belong in the gem itself and there an [issue open](https://github.com/mhenrixon/sidekiq-unique-jobs/issues/14) about this problem. My thought is to reply to the issue and lend our weight behind getting the gem changed. If it's not a hard fix I may be open to trying to collaborate with the gem authors to get it in.

### CODE REVIEW

**Comment by twinge** [comment]
Clean up rubocop failures, then :+1:

**Comment by soberstadt** [comment]
Since you're touching `lower_retry_worker` and `mail_chimp_worker` it looks like they are pretty much the same class except a few little changes. Could we move the shared behavior to parent class and inherent it down?

That might mean renaming mail_chimp_worker to something like RetryWorker, since it doesn't have any mail chimp specific code.

**Comment by draffensperger** [comment]
I looked and `MailChimpWorker` is actually only used in `AccountList` for subscribing/unsubscribing to the special MPDX user list mailchimp accounts. We can replace it with calls to `async`, though we should make sure it all works correctly once we stage it.

**Comment by draffensperger** [comment]
I just realized, a reason why that was probably done was so that those mail chimp account updates would be on the default queue rather than the import queue and be executed right away. Let me think some more about it.

**Comment by soberstadt** [comment]
Yeah, I believe they are different classes so they can be prioritized. We can still have the Mail Chimp Worker class, but it wouldn't have any additional code.

**Comment by twinge** [comment]
You're both correct about the motive for separate classes being the higher priority queue.

**Comment by draffensperger** [comment]
So my current suggestion then is to provide another method `async_to_queue` which allows you to directly specify the queue to run the code on. The only other difference for `MailChimpWorker` then is to have `backtrace: true` (record error backtraces), but I think we may as well do that by default for all jobs.

**Comment by draffensperger** [comment]
@twinge does this removal of `MailChimpWorker` and replacing with `async_to_queue` look good to you?

**Comment by twinge** [comment]
:+1:

**Comment by draffensperger** [comment]
I'm planning to merge this into `design-v2` once we rebase it on master. I think it would be good to get it tested in stage before we merge it to master.

**Comment by draffensperger** [comment]
I did some local testing and corrected a mistake in the `async_to_queue` calls. The checks for jobs being retried and existing older jobs running worked correctly. Because the Google contacts job is still causing a sync loop and I suspect duplicate jobs may be a partial cause, I'm planning to merge this to master tomorrow morning unless there are objections.

**Comment by twinge** [comment]
:+1:  Thanks for testing that locally

**Pull request merged**
