### PR TITLE
New action option prayer request

### PR DESCRIPTION
**Pull request by chencuicru**

### CODE REVIEW

**Comment by soberstadt** [comment]
I think I would personally prefer just 'Prayer Request' as the folllow-up action instead of 'Prayer Request Again' the phase seems kinda awkward IMO.

**Comment by twinge** [comment]
I don't like the idea of having prayer requests in my task list.

**Comment by draffensperger** [comment]
Yeah, I wouldn't really use it in my to do list either. I typically try to either pray for people right away when the request comes up or if it's really important put it in some other personal prayer list. But Tnt does have "Prayer" as one of the task options.

**Comment by soberstadt** [comment]
Looks good to me. Josh and I decided we can go ahead with this now and look to break prayer requests off in the future.

**Pull request merged**
