### PR TITLE
Use guard-zeus & Rubocop autocorrect, fix dup watched dir err

### PR DESCRIPTION
**Pull request by draffensperger**
These are changes to make development using `guard` easier. 

- Pull in `guard-zeus` which runs the `zeus` server in the background to pre-load rails
- Explicitly specify the directories to watch and thus exclude `node_modules` which was causing a duplicate watched directory error for me.
- Turn on the Rubocop autocorrect. My opinion is that the convenience of the autocorrect outweighs any downsides of it, especially with the newly enabled whitespace cops. But let me know if you think otherwise and perhaps we can set it per-user or something.

### CODE REVIEW

**Comment by draffensperger** [comment]
One side effect of having Guard not watch the full mpdx working directory was that it didn't Rubocop on things like `Guardfile`, `Rakefile`, etc. The better fix I found was to re-install the nodejs modules without symlinks via `npm install --no-bin-link` which prevents the duplicate directory watch errors.

**Comment by twinge** [comment]
can we use spring instead of zeus since that's what's bundled with current rails versions?

**Comment by draffensperger** [comment]
I had thought zeus was faster or better in some way before, but I tried timing both spring and zeus locally and they were very comparable and using spring reduces our dependencies and we are following the rails community's default suggestion.

**Comment by draffensperger** [comment]
Sorry, I just noticed that we had originally been using `spring rspec` all along (I guess I hadn't really understood what it was doing). So ultimately, this PR only introduces Rubocop autocorrect.

**Comment by draffensperger** [comment]
I'm just going to close this PR and re-open one with a clean branch name and commit to make the history clear.

**Pull request closed without merging**
